version: '3.9'
services:
  selenium-chrome:
    build: .
    ports:
      - "5900:5900" # Expose VNC port
      - "4444:4444" # If you need to expose the Selenium port
    volumes:
      - .:/usr/src/app
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug # If you want to see Selenium logs
      # Set a password for the VNC server (change 'secret' to a password of your choice)
      - VNC_NO_PASSWORD=1
